{{- if .Values.security.jwtlet.enabled }}
# Service account for the jwtlet server itself
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwtlet-sa
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used as the token subject for CFM
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cfm-agents
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used for various seed jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seed-jobs
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used by the controlplane to authenticate to Vault (token exchange)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controlplane
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: controlplane
    type: edcv-app
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used by the identityhub to authenticate to Vault (token exchange)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identityhub
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: identityhub
    type: edcv-app
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used by the issuerservice to authenticate to Vault (token exchange)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: issuerservice
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: issuerservice
    type: edcv-app
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account used for the Redline client app
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redline
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
---
# Vault's own service account (needed for Kubernetes auth method)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
---
# Service account for the siglet app (centralized here)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: siglet-sa
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
{{- end }}
