{{- if .Values.edc.siglet.enabled }}
#
# Copyright (c) 2026 Metaform Systems, Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#      Metaform Systems, Inc. - initial API and implementation
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: siglet-config
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
data:
  siglet.toml: |
    [token]
    server_secret = "93d22865c1b0695d3caa1ac5ba648b88942aaeee3b05ba4aff2efc87e2cd1944"
    [storage_backend]
    type = "postgres-vault"
    url = "postgresql://siglet:siglet@{{ include "cpd.pgHost" . }}:{{ .Values.postgresql.connection.port }}/sigletdb"
    [[transfer_types]]
    transfer_type = "HttpData-PULL"
    endpoint_type = "HTTP"
    endpoint = "http://provider:8080/data"
    token_source = "provider"
    [signaling_auth]
    mode = "disabled"
    [management_api_auth]
    mode = "enabled"
    jwks_url = "http://{{ include "cpd.fqdn" (dict "svc" "jwtlet" "ctx" $) }}:8080/.well-known/jwks.json"
    audience = "{{ .Values.global.tokenExchangeAudience }}"
{{- end }}
