{{- if .Values.telemetry.loki.enabled }}
{{- $c := .Values.telemetry.loki }}
{{- $name := include "cpd.fullname" (dict "name" "loki" "ctx" $) }}
{{- $configName := include "cpd.fullname" (dict "name" "loki-config" "ctx" $) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: {{ $name }}
    platform: edcv
    type: edcv-infra
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      name: {{ $name }}
      labels:
        app: {{ $name }}
        platform: edcv
        type: edcv-infra
    spec:
      containers:
        - name: loki
          image: {{ $c.image }}
          imagePullPolicy: {{ .Values.telemetry.imagePullPolicy }}
          args:
            - -config.file=/etc/loki/config.yaml
          ports:
            - containerPort: 3100
              protocol: TCP
              name: http
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
      volumes:
        - name: loki-config
          configMap:
            name: {{ $configName }}
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /tmp/loki

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /tmp/loki/chunks
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: 3100
      targetPort: 3100
{{- if .Values.security.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.global.gatewayName }}
  hostnames:
    - {{ $c.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $name }}
          port: 3100
{{- end }}
{{- end }}
