{{- if .Values.telemetry.prometheus.enabled }}
{{- $c := .Values.telemetry.prometheus }}
{{- $name := include "cpd.fullname" (dict "name" "prometheus" "ctx" $) }}
{{- $configName := include "cpd.fullname" (dict "name" "prometheus-config" "ctx" $) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    app: {{ $name }}
    platform: edcv
    type: edcv-infra
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      name: {{ $name }}
      labels:
        app: {{ $name }}
        platform: edcv
        type: edcv-infra
    spec:
      containers:
        - name: prometheus
          image: {{ $c.image }}
          imagePullPolicy: {{ .Values.telemetry.imagePullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-otlp-receiver
          ports:
            - containerPort: 9090
              protocol: TCP
              name: http
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ $configName }}
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - name: http
      port: 9090
      targetPort: 9090
{{- if .Values.security.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ include "cpd.namespace" . }}
  labels:
    {{- include "cpd.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.global.gatewayName }}
  hostnames:
    - {{ $c.host }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $name }}
          port: 9090
{{- end }}
{{- end }}
